from __future__ import annotations

PUZZLE_LABELS = {
    "quick_math": "Quick Math",
    "missing_number": "Missing Number",
    "puzzle_fit": "Puzzle Fit",
    "find_the_exit": "Find the Exit",
    "memory_challenge": "Memory Challenge",
    "flash_count": "Flash Count",
    "lucky_pick": "Lucky Pick",
    "hidden_motion_hunt": "Hidden Motion Hunt",
    "bounce_arena": "Bounce Arena",
    "cube_count": "Cube Count",
    "line_follow": "Line Follow",
    "chess_mate": "Chess: Mate in 1",
    "matchstick": "Matchstick Math",
    "cup_shuffle": "Cup Shuffle",
    "shade_spot": "Shade Spot",
    "mind_mix": "Mind Mix",
    "laser_maze": "Laser Maze",
}

ACTIVE_PUZZLE_TYPES = (
    "quick_math", "missing_number", "find_the_exit", "flash_count", "lucky_pick",
    "hidden_motion_hunt", "bounce_arena", "cube_count", "line_follow", "chess_mate", "matchstick", "cup_shuffle",
    "mind_mix", "laser_maze",
)  # Line Follow was removed once and brought back by the user (Weave V5, Hard only)
# Paused at the user's request (they lost views on their own and now share the Mind Mix video): off the selector, the
# Mixed pool and batch production, but still generated by Mind Mix, the Brain Test, and old records.
PAUSED_PUZZLE_TYPES = ("puzzle_fit", "memory_challenge", "shade_spot")
MIXED_PUZZLE_TYPES = tuple(kind for kind in ACTIVE_PUZZLE_TYPES
                           if kind not in ("hidden_motion_hunt", "bounce_arena", "chess_mate", "matchstick", "cup_shuffle", "mind_mix",
                                         "laser_maze"))
EXPERIMENTAL_PUZZLE_TYPES: tuple[str, ...] = ()
SUPPORTED_PUZZLE_TYPES = ACTIVE_PUZZLE_TYPES + PAUSED_PUZZLE_TYPES + EXPERIMENTAL_PUZZLE_TYPES


def active_type_labels() -> dict[str, str]:
    return {PUZZLE_LABELS[kind]: kind for kind in ACTIVE_PUZZLE_TYPES}
